### ISSUE TITLE
Create ActiveRecord 4 variant of adapter

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/activerecord-cockroachdb-adapter#11]
This adapter only supports ActiveRecord 5. There are lots of apps that haven't upgraded to ActiveRecord 5 yet and may not want to, so we should create a variant of the adapter that supports ActiveRecord 4.

There are some minor internal API differences between AR 4 and 5 which is why the current adapter doesn't work.

**Comment by jetware** [comment]
Here are rails version dependencies for the latest RoR apps versions from our repo:

publify-8.3.3: gem 'rails', '~> 4.2.5'
solidus-2.2.1: gem 'rails', '~> 5.0.0'
spree-3.2.1: gem 'rails', '~> 5.0.0'
redmine-3.1.7 -  redmine-3.3.3: gem "rails", "4.2.7.1"
redmine-2.6.10: gem "rails", "3.2.22.2"
tracks-2.3.0: gem 'rails', '~> 4.1.11'

The most popular, for sure, is redmine 3.3 with dependency on rails 4.2.7.1.

If you could create AR 4 variant of adapter, we'd try to build Redmine bundles with CockroachDB, and run our test and benchmarks on it. We'd be happy to provide CockroachDB as alternative to MySQL or PostgreSQL in our RoR-app and RoR-stacks constructors.

**Comment by petermattis** [comment]
@jordanlewis How much work would it be to create an ActiveRecord 4 adapter? We had another request for this come in yesterday from a user who can't upgrade to ActiveRecord 5 easily.

**Comment by jordanlewis** [comment]
Probably not too much, but as is usual for these kinds of projects, the complexity is hidden and may reveal itself further once work begins. I have an in progress branch for this and I still intend to get to it soon.

**Comment by irfansharif** [comment]
Closing in light of https://github.com/cockroachdb/activerecord-cockroachdb-adapter/tree/0.1.x. Perhaps this deserves a shoutout in the `master` README branch, or have `master` fast forwarded to head. Thanks for getting this done, can finally play around with this!
