### ISSUE TITLE
Uuid for unique ids in Rails 5.x fails due to direct inheritance with PostgreSQL adapter

### ISSUE THREAD

**Issue by mcansky** [cockroachdb/activerecord-cockroachdb-adapter#12]
Rails 5.x has first class support for uuid as unique ID for objects. PostgreSQL 9.4+ has a direct support of that through a call to gen_random_uuid() in the create query :

```
CREATE TABLE "users" ("id" uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY, "email" character varying, [...]
```

Unfortunately that function doesn't exist in the case of cockroachdb. Instead, as pointed out in the documentation (https://www.cockroachlabs.com/docs/v1.1/uuid.html#create-a-table-with-auto-generated-unique-row-ids) uuid_v4()::UUID() should be used.

## a quick work around

As described in the postgresql adapter code (https://github.com/rails/rails/blob/8f037a5ab929f929fe0897edc9ecadf901c32e56/activerecord/lib/active_record/connection_adapters/postgresql/schema_definitions.rb#L7-L45) it's possible to pass a custom function name to handle uuid generation.

So, to get through with the create the migration should look like this :

```
create_table :users, id: false do
  t.primary_key :id, :uuid, default: "uuid_v4()::UUID"
  [...]
end
```

## permanent fix

I'd guess one needs to add something similar to https://github.com/rails/rails/blob/8f037a5ab929f929fe0897edc9ecadf901c32e56/activerecord/lib/active_record/connection_adapters/postgresql/schema_definitions.rb#L46-L52 for this adapter. I might have a try if someone can validate this thought.

**Comment by tamird** [comment]
Looks like gen_random_uuid is just an alias of uuid_v4, perhaps with
stronger "randomness". Maybe the right thing is to implement that function
in CRDB.

**Comment by jordanlewis** [comment]
+1 to @tamird's suggestion - we'll implement that builtin in CockroachDB.

**Comment by mcansky** [comment]
@jordanlewis , @tamird : ok, I am split though, check my PR and close it if you think it's better to keep this adapter as close as possible to the postgresql one.

**Comment by benesch** [comment]
Agreed that we should add the builtin—unless there are cryptographic guarantees that we don't provide?—but that won't make it in until 1.2, no? Patching the adapter would make things work today.

**Comment by mcansky** [comment]
@benesch : patching the adapter would make it work out of the box faster yes; if someone can point me to some documentation or give me a hand in #13 it could be ready soon

**Comment by mcansky** [comment]
@jordanlewis @benesch : can we close #13 or are we going to do something with it ?

**Comment by jordanlewis** [comment]
Hi @mcansky, sorry for the slow response here. Thanks a lot for sending that PR - I really appreciate you pitching in.

We ended up implementing the builtin in CockroachDB in PR https://github.com/cockroachdb/cockroach/pull/19379.

We'll get this cherry-picked into the next patch release of 1.1, so you shouldn't have to wait too long.

**Comment by mcansky** [comment]
@jordanlewis : very good very good; good work people ! 👍

**Comment by sandstrom** [comment]
Is this still an issue, or can we close this?

I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by jordanlewis** [comment]
@rafiss PTAL - can we close this?

**Comment by rafiss** [comment]
Yes, this should be resolved.
