### ISSUE TITLE
No changelog and tags

### ISSUE THREAD

**Issue by flavio** [cockroachdb/activerecord-cockroachdb-adapter#14]
Could you provide a changelog about what changed between the different release and also tag them.

Right now on rubygems there are several releases but it's not possible to know what changed in between.

**Comment by lego** [comment]
Hey, thanks for this @flavio. I've opened another issue (https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/18) to track a handful of other things that I hope to get also get to for improving this gem :). Feel free to toss any other improvements into there and I'll happily add it to the list.

I do agree that this gem is a little not quite maintained at the moment, and one of the things that I want to do is improve that. I appreciate your help here!
