### ISSUE TITLE
Support for geospatial

### ISSUE THREAD

**Issue by dbist** [cockroachdb/activerecord-cockroachdb-adapter#151]
having the following data type in my schema `    t.geography "from_geopoint", limit: {:srid=>0, :type=>"geometry"}` throws the following error in migration `unknown OID 90002: failed to recognize type of 'from_geopoint'. It will be treated as String.`

**Comment by otan** [comment]
it cannot be part of an index or PK. only can be part of an inverted index (for now). inverted index is the only way spatial data gets accelerated (this is the same as for JSONB/ARRAY types we have today).

see https://github.com/cockroachdb/cockroach/issues/50659

**Comment by dbist** [comment]
@otan this is a separate issue, during a migration cockroachdb adapter throws this error where the schema would include a field with geometry type.

**Comment by otan** [comment]
oops, sorry!

**Comment by otan** [comment]
the fix for this is to fork `activerecord-spatial` and use that instead

https://github.com/dark-panda/activerecord-spatial

**Comment by dbist** [comment]
does that mean to fork on the adapter level or the application level?

**Comment by otan** [comment]
the adapter might "just work". likely not though.
but i'm also not sure why activerecord cannot seem to handle a new type we introduced -- does it work for ENUMs/STRING fields?

**Comment by vy-ton** [comment]
@otan I'm trying to understand the difference between https://github.com/dark-panda/activerecord-spatial and https://github.com/rgeo/activerecord-postgis-adapter. 

When I was only aware of `activerecord-postgis-adapter`, I understood the ActiveRecord PostGIS adapter supported new spatial types/features. But looking at `activerecord-spatial`, it sounds it uses the regular Postgres Active Record adapter. Does each library support different functionality?

cc @awoods187

**Comment by vy-ton** [comment]
CockroachDB’s Active Record adapter v5.2.2 and v6.0.0beta3 now support spatial data with RGeo, the spatial data library for Ruby, integration.
