### ISSUE TITLE
Use built-in function before releasing 5.x with spatial support and 6.x GA release

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/activerecord-cockroachdb-adapter#169]
After https://github.com/cockroachdb/cockroach/issues/57480 is available, the function should be called from within the Active Record adapter code. Ideally, the arbitrary string should detect

- use of v5.x adapter
- use of v6.x adapter
- use of RGeo/PostGIS functionality (is there somewhere this could hook in?)

**Comment by sandstrom** [comment]
I think the blocker is gone now:
https://github.com/cockroachdb/cockroach/pull/59768

**Comment by rafiss** [comment]
@solongordon will look into doing this; or else delegate to Keith if needed.

**Comment by vy-ton** [comment]
@solongordon Do you plan on backporting https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/196 to 5.2 as well?
