### ISSUE TITLE
Rails 6.1 support

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#170]
Hello,

Rails 6.1 has been out for a few weeks now.

When can we expect an update of the cockroachdb adapter?
Without this we cant update our applications to Rais 6.1.

Thank you

**Comment by vy-ton** [comment]
@Piioo Our team is taking a look, we should have an update in a few weeks.

**Comment by vy-ton** [comment]
@Piioo CockroachDB’s Active Record adapter v6.1.0beta1 now includes beta support for Rails 6.1. Please try it out and report any issues.

**Comment by carlallen** [comment]
Using 6.1.0.pre.beta.3, decimals are being cast to integers.

**Comment by vy-ton** [comment]
@keithdoggett Can you take a look at the decimal to integer cast issue?

**Comment by keithdoggett** [comment]
@vy-ton, @carlallen opened #197 which fixes the issue. I've given it a look and it should be good, but we should get someone else to review it as well.

**Comment by Piioo** [comment]
Thanks @vy-ton it seams to work. I have not checked the cast, only the update for our purpose

**Comment by emmahsax** [comment]
@Piioo It looks like [as of 2021-04-26](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/commit/3824f866615d4aab9c6cb0f7cd5200063b4e7b42) the `master` branch is officially Rails 6.1 compatible. The release is not out yet though. But if you could pull straight from the `master` branch, maybe you could get the update.

**Comment by rafiss** [comment]
@emmahsax We also published the release on rubygems earlier this week: https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/

I just created a release on Github as well. I'll close this issue, and the fix from #197 should be released later.

Thanks for your patience for Rails 6.1 support everyone!
