### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by sandstrom** [cockroachdb/activerecord-cockroachdb-adapter#180]
Thanks for an awesome adapter! 🏅 

Maybe you could add a changelog, with name and date of release + release notes.

https://keepachangelog.com/en/1.0.0/

#### Minor nitpicks 

- Would also be nice if you'd fill in the gaps in releases. Right now there is `v6.1.0beta1` and `v6.0.0beta3` but no `v6.0.0`.

- Also, semver is usually `1.0.0-beta.1` (https://semver.org/#spec-item-9).

**Comment by rafiss** [comment]
Thanks for filing this!

We will definitely be filling in the gaps in the releases. Right now we do intentionally have beta releases for both 6.0 and 6.1. The idea is that adapter version `X.Y` is compatible with Rails version `X.Y`.

A changelog would be excellent. We'll work on it.

**Comment by rafiss** [comment]
v6.1.0-beta.2 was just published using semver and including a changelog.

(non-beta releases for v6.0 and v6.1 will still be coming in the future)

**Comment by sandstrom** [comment]
awesome @rafiss 😄
