### ISSUE TITLE
Consistent tag/release naming

### ISSUE THREAD

**Issue by sandstrom** [cockroachdb/activerecord-cockroachdb-adapter#187]
Thanks for a great project! 🎖️ 

Perhaps you could normalize the tag naming?

Right now you have three different formats mixed: `vX.Y.Z-beta.N`, `vX.Y.ZbetaN` and `vX.Y.Z.betaN`.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/122287/110220542-8da5a680-7ec6-11eb-9e38-ece49dba2c05.png">

Semver recommends `vX.Y.Z-beta.N` [source](https://semver.org/#spec-item-9).

I'd suggest simply renaming the old tags with a new, consistent format.

***

You should probably also normalize the gem version naming you use:
https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions

**Comment by rafiss** [comment]
I can go ahead and apply consistent git tags to past releases. However, I don't think we will be changing any of the published gems. Though it's unfortunate that we didn't use correct semver for those versions, we already have some users who are pointing at the existing published version numbers and changing the numbers could break things for those users.

**Comment by sandstrom** [comment]
Great! 

Yeah, I wouldn't change any gems either (at least not now).
