### ISSUE TITLE
Missing comments after migrations in the schema.rb

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#201]
Hello,

we are working with comments for columns in the tables.
`add_column :my_table, :code, :string, comment: "Its a code"`

Then the comment is written into the schema.rb. This is fine.

But after the next migration the comment is removed from the schema.rb (`rails db:migrate`)

It is annoying to revert all the comments in our schema.rb and let only the real changes in it :)

**Comment by keithdoggett** [comment]
Looks like comments are disabled https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/3824f866615d4aab9c6cb0f7cd5200063b4e7b42/lib/active_record/connection_adapters/cockroachdb_adapter.rb#L177-L185

Although the linked issue has been closed, so it should be safe to remove those methods. I can go through all of those settings and get a PR together soon.

**Comment by keithdoggett** [comment]
Support for this is being added in #195

**Comment by Piioo** [comment]
seems to be fixed.
