### ISSUE TITLE
Cockroach doesn't support SELECT FOR UPDATE

### ISSUE THREAD

**Issue by DavidSie** [cockroachdb/activerecord-cockroachdb-adapter#21]
Hello I have an app that uses you adapter.
There is a following problem:
```sql
D, [2018-03-02T10:47:08.279117 #38] DEBUG -- : [6f444444-44d2-4aad-b9d1-ac0aae5c3fae]   Doorkeeper::AccessGrant Load (1.0ms)  SELECT  "something_access_grants".* FROM "something_access_grants" WHERE "something_access_grants"."id" = $1 LIMIT $2 FOR UPDATE  [["id", SOMEID], ["LIMIT", 1]]
D, [2018-03-02T10:47:08.279935 #38] DEBUG -- : [6f444444-44d2-4aad-b9d1-ac0aae5c3fae]    (0.6ms)  ROLLBACK
I, [2018-03-02T10:47:08.280114 #38]  INFO -- : [6f444444-44d2-4aad-b9d1-ac0aae5c3fae] Completed 500 Internal Server Error in 14ms
F, [2018-03-02T10:47:08.282341 #38] FATAL -- : [6f444444-44d2-4aad-b9d1-ac0aae5c3fae]   
F, [2018-03-02T10:47:08.282397 #38] FATAL -- : [6f444444-44d2-4aad-b9d1-ac0aae5c3fae] ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  syntax error at or near "for"
DETAIL:  source SQL:
SELECT  "something_access_grants".* FROM "something_access_grants" WHERE "something_access_grants"."id" = $1 LIMIT $2 FOR UPDATE
```

I am using cockroach cluster with version 1.1.5.
Cockroachdb does not have `SELECT FOR UPDATE` in its SQL dialect.
Correct me if I am wrong, but I think it does not need it since it has serialised transactions.

Can you fix your adapter to not use `SELECT FOR UPDATE` ? 
Thanks :)

**Comment by asubiotto** [comment]
@DavidSie [here is the RFC for `SELECT FOR UPDATE`](https://github.com/rytaft/cockroach/blob/a8760c386c74b746bb7bc50ee7e86bde75cc6dd1/docs/RFCS/20171024_select_for_update.md#drawbacks), the decision made was to postpone the work. Thanks for bringing this to our attention.

cc @jordanlewis

**Comment by jordanlewis** [comment]
Thanks for the report. You're right that we should prevent the adapter from emitting `FOR UPDATE` clauses.

**Comment by bpieck** [comment]
I needed to circumvent this, too. I don't know, if my way maybe helps to figure best way to fix it better in this adapter - but if so:
I monkey patched ActiveRecord::Base directly by using following code snippet:

```
module ActiveRecord
  class Base
    def lock!
      super unless self.class.connection.class.to_s == 'ActiveRecord::ConnectionAdapters::CockroachDBAdapter'
    end
  end
end
```

**Comment by donbowman** [comment]
support in cockroachdb to make it a no-op was just merged https://github.com/cockroachdb/cockroach/pull/40206
