### ISSUE TITLE
Rails .explain delivers only the tree

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#211]
Hello,

when I run `Foo.where(bar: 1).explain` I got only the tree without the additional informations.

The informations are there, when I run the query with `ActiveRecord::Base.connection.execute`...

It seams that the `.explain` method is not display the additional informations.

<img width="603" alt="Bildschirmfoto 2021-06-14 um 10 08 27" src="https://user-images.githubusercontent.com/4640423/121860534-3ac76080-ccf9-11eb-9c2f-ddbbc26deea2.png">

**Comment by keithdoggett** [comment]
I tried this with Rails 6.1 on Cockroach 21.1 and it seemed to work for me

```
irb(main):008:0> User.where(code: 'abc').explain
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."code" = $1  [["code", "abc"]]
=> 
EXPLAIN for: SELECT "users".* FROM "users" WHERE "users"."code" = $1 [["code", "abc"]]
            info
----------------------------
 distribution: full
 vectorized: true
 
 • filter
 │ filter: code = 'abc'
 │
 └── • scan
       missing stats
       table: users@primary
       spans: FULL SCAN
(10 rows)
```

What version of ActiveRecord are you using? Are there any other gems installed that override `explain` that might not be playing nice with the different formatting between Postgres and Cockroach explain plans?

**Comment by Piioo** [comment]
ok, thanks. Im still waiting for the DB update.

**Comment by Piioo** [comment]
It is working with 21.1
