### ISSUE TITLE
Model.new doesn't set default values

### ISSUE THREAD

**Issue by FX-HAO** [cockroachdb/activerecord-cockroachdb-adapter#223]
Rails version: 5.2.6
activerecord-cockroachdb-adapter: 5.2.3
CRDB: v21.1.7 (x86_64-unknown-linux-gnu, built 2021/08/09 17:55:28, go1.15.14)

`Model.new` doesn't set default values. 
And `Model.create` creates a record without setting default values. we have to call `reload` to retrieve default values.

migration:
```
create_table :orders do |t|
  t.decimal :amount, precision: 32, scale: 16, default: 0
end
```

model:
```
class Order < ApplicationRecord
end
```

open a rails console
```
order = Order.new
puts order.amount # returned nil, should be 0.0

order = Order.create
puts order.amount # returned nil, should be 0.0
puts order.reload.amount # returned 0.0
```

**Comment by rafiss** [comment]
Thanks for reporting and finding this!

If you'd like to make a PR, that'd be great. Otherwise we'll look at this closer later.

cc @keithdoggett
