### ISSUE TITLE
Reenabling referencial integrity fails with Ruby 3

### ISSUE THREAD

**Issue by arbesulo** [cockroachdb/activerecord-cockroachdb-adapter#228]
I got into this when trying to run the tests in my project (using activerecord-cockroachdb-adapter v6.1.3 ) 

ActiveStorage is used in the project, which adds following foreign keys:

```ruby
  add_foreign_key "active_storage_attachments", "active_storage_blobs", column: "blob_id"
  add_foreign_key "active_storage_variant_records", "active_storage_blobs", column: "blob_id"
```

when  starting the test suite, a call `DatabaseCleaner.clean_with(:truncation)` is issued , which ends raising the following error:

```bash
ArgumentError:
  wrong number of arguments (given 3, expected 2)

in /Users/fer/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-cockroachdb-adapter-6.1.3/lib/active_record/connection_adapters/cockroachdb/referential_integrity.rb:25
```

It looks like it is caused by wrongly passed Keyword Arguments to the method:

```ruby
add_foreign_key(foreign_key.from_table, foreign_key.to_table, foreign_key.options)
```

it should be something similar to

```ruby
add_foreign_key(foreign_key.from_table, foreign_key.to_table, **foreign_key.options)
```

**Comment by sandstrom** [comment]
@arbesulo Was this solved by https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/230?

**Comment by arbesulo** [comment]
yep, solved. Thanks a lot!
