### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  unknown variable: "max_identifier_length"

### ISSUE THREAD

**Issue by bpieck** [cockroachdb/activerecord-cockroachdb-adapter#23]
For rails 5.1 you overwrote table_alias_length - but missed max_identifier_length.
I ran into above issue with this adapter and rails 5.1.5. I saw you already fixed this in some similar case - but it seems it came back again.

I checked with a monkey_patch on CockroachDBAdapter

```
alias max_identifier_length table_alias_length
```

Then it's working again.

**Comment by bherrup** [comment]
Having the same issue.   thanks @bpieck

**Comment by phosphor1879** [comment]
@bpieck I am running into this issue for past few days. I've tried monkey patching to no avail. Any hints would be appreciated.

**Comment by bpieck** [comment]
Hm, the monkey patch above is not needed anymore (as @phosphor1879 mentioned).
So what is your issue in detail @Iqlaas ? Maybe I can help.

**Comment by Iqlaas** [comment]
Hey @bpieck . Thank you so much. Dropped you an email.

**Comment by robly** [comment]
We are also seeing this error. 

build:               CCL v2.0.5 @ 2018/08/13 17:59:42 (go1.10)

activerecord-cockroachdb-adapter (0.2.2)
