### ISSUE TITLE
Rails 7 Support

### ISSUE THREAD

**Issue by conradwt** [cockroachdb/activerecord-cockroachdb-adapter#239]
Are there plans for a version of `activerecord-cockroachdb-adapter` gem that supports Rails 7?

**Comment by keithdoggett** [comment]
Hi, @conradwt there is a PR open that makes changes for ActiveRecord 7 support (#227). It should be reviewed and merged soon.

**Comment by Piioo** [comment]
3 months later

**Comment by jayzalowitz** [comment]
This is now blocking a lot of work at my company.

**Comment by JorgenIvarsson** [comment]
Looking forward to an updated version with support for Rails 7. I am currently stuck:
When running 'bundle install':
"In Gemfile:
    activerecord-cockroachdb-adapter (~> 6.1.0) was resolved to 6.1.10, which depends on
      activerecord (~> 6.1)

    rails (~> 7.0.3) was resolved to 7.0.3, which depends on
      activerecord (= 7.0.3)"

**Comment by sandstrom** [comment]
I think this may be fixed in #252, feel free to close if that's the case.

**Comment by conradwt** [comment]
@sandstrom This works but I'm waiting for an official release of this gem because I prefer to pin my gems to an explicit released tag.  At this time, I'm only seeing v6.1.2.

**Comment by rafiss** [comment]
We published the gem back in July, so closing this
https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/7.0.0

**Comment by sandstrom** [comment]
@rafiss Awesome!

I've been eying CockroachDB for a few years now, for a Rails app. But with all the failing tests (https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48), I feel some uncertainty about porting. Risk is that we discover some blocker half-way through a multi-month migration 😅  

Are you aware of any large Rails applications (>100k LOC) that are using it in production?

Would you say that this adapter is in a "complete" state right now? Or is it more of a management decision that it hasn't gotten that much attention lately?

**Comment by rafiss** [comment]
Yes we have customers using the adapter in production. I don't know how many lines of code they have, but I do know that many of them have dozens of engineers working on their product.

The failing tests from https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/48 are largely due to differences in CockroachDB versus Postgres, or functionality that CockroachDB doesn't have that Postgres doesn't. If your app doesn't use that functionality (also described at https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html) then you should be fine.

Yes, the adapter is complete and supported for v7.0, v6.1, and v6.0 of Rails.

**Comment by sandstrom** [comment]
Thanks for the update @rafiss!

When we investigated the difference about a year ago, I remember that there were some problems with this adapter (many which I think are now solved, for example with migrations/join tables/composite primary keys).

There were also two issues in CockroachDB (outside this adapter):
- https://github.com/cockroachdb/cockroach/issues/41522 [NOTIFY, LISTEN, and UNLISTEN]
- https://github.com/cockroachdb/cockroach/issues/13546 [pg_advisory_lock]

**Comment by rafiss** [comment]
Thanks for the further details! That's right, those two CRDB issues you linked are not yet completed, and we haven't yet made plans to work on them.
