### ISSUE TITLE
Update max_identifier_length length to 128

### ISSUE THREAD

**Issue by Woolworths** [cockroachdb/activerecord-cockroachdb-adapter#260]
As you can see here:
- https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/abstract/database_limits.rb

`max_identifier_length` is set to 64, however when I run in CockroachDB:
`SHOW max_identifier_length;`

I get `128`. I believe max_identifier_length should be updated from 64 to 128.

**Comment by Woolworths** [comment]
Note that 128 is not the "enforceable" limit, but may be enforceable in the future, see here:
https://www.cockroachlabs.com/docs/stable/schema-design-overview.html#hard-limits

**Comment by amozoss** [comment]
Ran into this today, I'm using Rails to do some things with an existing cockroach database, so I don't have any control over the index names. 

The index name is clearly valid for cockroach because everything works fine when the server is running, but when trying to run a test rails throws an error.

```
ArgumentError: Index name 'bucket_bandwidth_rollups_archive_action_interval_project_id_index' on table 'bucket_bandwidth_rollup_archives' is too long; the limit is 63 characters (ArgumentError)                                                                          
                                                                                                                                                                                                                                                                           
            raise ArgumentError, "Index name '#{new_name}' on table '#{table_name}' is too long; the limit is #{index_name_length} characters"                                                                                                                             
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by BuonOmo** [comment]
You all are pretty right, this was overriden when cockroachdb didn't have support for `SHOW max_identifier_length`. Let's now fallback to the default pg adapter behaviour
