### ISSUE TITLE
Cockroach plans for ActiveRecord

### ISSUE THREAD

**Issue by sandstrom** [cockroachdb/activerecord-cockroachdb-adapter#261]
What are the Cockroach-teams plans for this repo?

It hasn't seen a release in almost a year, and some issues are left unanswered. Have you moved priorities elsewhere?

For someone evaluating a potential switch to CockroachDB, we'd like to understand:

- What's your plan or roadmap for this adapter?
- How many developers do you currently have working on this adapter?
- What's your general plan for DB adapters? To maintain them yourself? Or rely on others to do the work for you?
- What are some planned changes to the core DB engine, that are relevant for this adapter?

**Comment by dikshant** [comment]
For database tools we use a combination of in house expertise, work with project maintainers etc for ongoing support.
For active record we have nightly tests in place that ensure DB related changes do not cause regressions in the adapter.
We are working on sourcing someone well versed in Ruby and ActiveRecord to maintain this adapter going forward.

**Comment by sandstrom** [comment]
@dikshant Sounds promising! 

I think that's a great idea! With a senior Ruby developer dedicated to this adapter, you could really make it shine and make the overall integration flow for Rails applications (and others using ActiveRecord) much better.

For us right now, we've unfortunately put CockroachDB on hold due to some missing pieces in the adapter. I'll keep my eyes out for updates!

Have a great week! 💯

**Comment by dikshant** [comment]
@sandstrom any particular features you are looking for?

**Comment by sandstrom** [comment]
For async job processing via something called [Good Job](https://github.com/bensheldon/good_job) to work, we'd need advisory locks (https://github.com/cockroachdb/cockroach/issues/13546) and notify/listen (https://github.com/cockroachdb/cockroach/issues/41522). 

Those are not related to the adapter though, it's a lack of functionality within CockroachDB proper.

More details:
https://github.com/bensheldon/good_job/discussions/292#discussioncomment-5432002

There was also an issue around rails migrations and transactions(?) with this adapter if I recall correctly, but I cannot find the issue or a description about it right now. Maybe it's solved (I don't have more than a few minutes to look for it at the moment).

Second was a problem with compound keys in the schema config file in Rails, and how this couldn't be setup for a join table (N-N relationship) without having a surplus `id` column (a regular join table should only have `table_a_id` and `table_b_id` foreign key columns, but with this bug a third `id` column was required even though it didn't serve a purpose). 

But this bug may also have been solved.
