### ISSUE TITLE
support for AOST queries

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/activerecord-cockroachdb-adapter#281]
CockroachDB has support for AS OF SYSTEM TIME timestamp queries. This can be prefixed to any SELECT query to query using the systemtime and get a historical view of the data. More info here:
https://www.cockroachlabs.com/docs/v1.1/as-of-system-time

It would be good to have support for AOST queries in ActiveRecord. Some potential approaches using select examples from [here](https://api.rubyonrails.org/v7.0.6/classes/ActiveRecord/QueryMethods.html#method-i-select):

```ruby
Model.select(:field).aost(some_timestamp)
Client.where("orders_count = '2'").aost(some_timestamp)
```

I am not 100% certain on if adding .aost method will break things or would be an antipattern in ActiveRecord/Ruby. cc: @BuonOmo for guidance on that.

**Comment by BuonOmo** [comment]
@dikshant I encountered an issue..

```ruby
Post.transaction { Post.aost(2.seconds.ago).take }
```

raises an error:

```
ERROR:  inconsistent AS OF SYSTEM TIME timestamp; expected: 1693509388.693543000,0, got: 1693509386.000000000,0 (PG::FeatureNotSupported)
HINT:  try SET TRANSACTION AS OF SYSTEM TIME
```

The PR for now is avoiding this error. But I think the feature as it is lacks the possibility of setting per transaction the system time. One can do it pretty easily though:

```ruby
Post.connection.execute('SET TRANSACTION AS OF SYSTEM TIME ...')
```

So IMHO, we should keep it like this and just be aware of the limitations of the feature. However, you might have more information on how this is used to know more about how we could design this feature!

**Comment by BuonOmo** [comment]
@rafiss @dikshant so on this support, we for now do not support:

1. special aost functions
2. Using aost in transactions

The first point is roughly an hour of code, and I'd be up to it if you want it.

The second one is way more complex as we'd have to first define the API we want, and it would be more code whatever the decision is. I've written detailed information about in my previous message. And thinking of solutions, here are some I have in mind (I didn't check for feasability yet):


# Set at transaction level

```ruby
Post.transaction(aost: time) do
  ...
```

# Implicit ruby magic

```ruby
Post.transaction do
  # Would check if in transaction and run the aost query, setting it
  # for every queries in the transaction implicitely
  post = Post.aost(time).first 
```

# Sugar

```ruby
Post.transaction do
  # Just syntactic sugar for:
  #
  #     Post.connection.execute('SET TRANSACTION AS OF SYSTEM TIME ...')
  #
  Post.connection.aost(time)

---

TBH, I think we should not do any of those, as the non-sugar version is quite clear, e.g:

```ruby
Post.connection.execute('SET TRANSACTION AS OF SYSTEM TIME ...')
```
