### ISSUE TITLE
AOST (As of System Time) Queries: support the other parameter types like an interval or any of the helper functions

### ISSUE THREAD

**Issue by nollenr** [cockroachdb/activerecord-cockroachdb-adapter#297]
The current commit only supports passing in an explicit timestamp as the parameter to AS OF SYSTEM TIME. It doesn't look to support the other [parameter types](https://www.cockroachlabs.com/docs/stable/as-of-system-time#parameters) like an interval or any of the helper functions.

**Comment by BuonOmo** [comment]
@nollenr absolutely. I wouldn't suggesting using this feature anyway as the is per query, and it is likely you are using transactions.

I don't have acces to a laptop now but I'll try to make some pseudo code :

```ruby
ApplicationRecord.connection.execute("set transaction ...")
```

Please refer to the doc you mentioned for the SQL syntax!

We could consider more features in that direction but seen the small footprint of this code i don't really see the benefits

**Comment by BuonOmo** [comment]
Closing for now due to low activity. Feel free to comment below if the feature feels important
