### ISSUE TITLE
Creating materialized views is possible since v20.2, yet the adapter returns `false`

### ISSUE THREAD

**Issue by MarcusRiemer** [cockroachdb/activerecord-cockroachdb-adapter#298]
We use Cockroach with [Scenic](https://github.com/scenic-views/scenic) and that seems to work just fine. But we sadly hat to monkey patch stuff because of (effectively) `supports_materialized_views? = false` in the Cockroach Rails driver. See: https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/9c4614125f2e11f60fcc2e1f11a09d17e31cd4cc/lib/active_record/connection_adapters/cockroachdb_adapter.rb#L180-L182

Given that 20.2 is out of support by now fixing this in a brute way seems possible: Would you take a PR that simply changes the implementation to `true`?

**Comment by dikshant** [comment]
Yep PRs are welcome!

**Comment by BuonOmo** [comment]
Closing in Favor of #336, I'm adding it there!
