### ISSUE TITLE
Consider supporting latest pg version

### ISSUE THREAD

**Issue by cabello** [cockroachdb/activerecord-cockroachdb-adapter#30]
Hi 👋 

The gem currently requires pg 0.21.0 from June 12, 2017 (209 KB) 
While 1.1.3 is the latest version of the pg gem released in September 07, 2018.

[gem Changelog](https://bitbucket.org/ged/ruby-pg/src/0fd7bb2494e8cc11c71c05f8f12deafa6b41fb37/History.rdoc?at=default&fileviewer=file-view-default)

We've been using pg 1.x for a while in production, it would be helpful to be able to use cockroachdb with the latest version of pg.

**Comment by BuonOmo** [comment]
Now pg `~> 1.2` is the supported version, hence the current latest (1.5.5) can be used.
