### ISSUE TITLE
crdb_internal in schema.rb

### ISSUE THREAD

**Issue by Piioo** [cockroachdb/activerecord-cockroachdb-adapter#314]
Hello,

I try to update our application to rails 7 and after gem updates and migrations in the schema.rb is `create_schema "crdb_internal"` added.

With this addition does `rails db:setup` which is used in CI and development not work anymore. 
It does not work, because crdb_internal already exists.

How I may avoid this line after migration?

```
ActiveRecord::Schema[7.1].define(version: 2024_02_12_145951) do
  create_schema "crdb_internal"
```

activerecord-cockroachdb-adapter (7.1.0)
rails (7.1.3)

After `rails db:drop` I cant do `db:setup` because of:
```
PG::DuplicateSchema: ERROR:  schema "crdb_internal" already exists (PG::DuplicateSchema)
```

**Comment by BuonOmo** [comment]
Hi @Piioo, thanks for pointing out this issue. There might have been a change in the `db:setup` rake command we overlooked.

I'm not sure I fully get you though, what were the steps that led you to this issue ? Could you setup a reproduction ? Here's the rails template for opening issues related to migrations: https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record_migrations.

**Comment by Piioo** [comment]
Your link is not working.

It is easy to reproduce:

1. create a new rails app with rails 7.1.x -> `rails new foo`
2. add `gem 'activerecord-cockroachdb-adapter'` to Gemfile 
3. Change the configuration `config/database.yml` file for cockroachdb
4. run `rails db:create db:migrate`


The result schema.rb is
```
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[7.1].define(version: 0) do
  create_schema "crdb_internal"

end
```

**Comment by BuonOmo** [comment]
Link fixed! Thanks for the reproduction, I'll try that soon, what is the error I shall encounter?

**Comment by Piioo** [comment]
The error is:

```
➜  bar git:(main) ✗ bundle exec rails db:drop db:setup
Dropped database 'test_dev'
Dropped database 'storage/test.sqlite3'
Created database 'test_dev'
Created database 'storage/test.sqlite3'
bin/rails aborted!
ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "crdb_internal" already exists (ActiveRecord::StatementInvalid)
/Users/pisz/work/rails/x-ion/tmp/bar/db/schema.rb:14:in `block in <main>'
/Users/pisz/work/rails/x-ion/tmp/bar/db/schema.rb:13:in `<main>'

Caused by:
PG::DuplicateSchema: ERROR:  schema "crdb_internal" already exists (PG::DuplicateSchema)
/Users/pisz/work/rails/x-ion/tmp/bar/db/schema.rb:14:in `block in <main>'
/Users/pisz/work/rails/x-ion/tmp/bar/db/schema.rb:13:in `<main>'
Tasks: TOP => db:setup => db:schema:load
(See full trace by running task with --trace)
```

The problem is that the CI load the database schema.

**Comment by BuonOmo** [comment]
Got you, I've tried https://github.com/cockroachdb/activerecord-cockroachdb-adapter/pull/316 with your reproduction, it works on my end. Would you like to verify as well directly in CI? Also, you can point to that branch if you don't want to wait for the next release!

**Comment by jayzalowitz** [comment]
same issue on my end 

web-1                  | bin/rails aborted!
web-1                  | ActiveRecord::StatementInvalid: PG::DuplicateSchema: ERROR:  schema "crdb_internal" already exists (ActiveRecord::StatementInvalid)
web-1                  | /app/db/schema.rb:14:in `block in <main>'
web-1                  | /app/db/schema.rb:13:in `<main>'
web-1                  | 
web-1                  | Caused by:
web-1                  | PG::DuplicateSchema: ERROR:  schema "crdb_internal" already exists (PG::DuplicateSchema)
web-1                  | /app/db/schema.rb:14:in `block in <main>'
web-1                  | /app/db/schema.rb:13:in `<main>'
web-1                  | Tasks: TOP => db:prepare
web-1                  | (See full trace by running task with --trace)
web-1 exited with code 1
@BuonOmo

**Comment by jayzalowitz** [comment]
> @jayzalowitz does the fix branch address the issue for you ? Hopefully we can merge it soon

tell me what I need to put in my gemfile and I can test for ya.

**Comment by BuonOmo** [comment]
@jayzalowitz you'd need to point to github:

```ruby
gem "activerecord-cockroachdb-adapter", github: "cockroachdb/activerecord-cockroachdb-adapter"
```

Optionnally you can set a `branch:` or `tag:` if you want to keep this for a while and be sure you don't get any update.

**Comment by jayzalowitz** [comment]
LGTM 
`web-1                  | == 20240327195749 CreateUsers: migrated (1.5325s) =============================
web-1                  | 
yarn install v1.22.19
warning package.json: No license field
warning flyflat-admin@1.0.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.31s.
web-1                  | => Booting Puma
web-1                  | => Rails 7.1.3.2 application starting in development 
web-1                  | => Run `bin/rails server --help` for more startup options
web-1                  | Puma starting in single mode...
web-1                  | * Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
web-1                  | *  Min threads: 5
web-1                  | *  Max threads: 5
web-1                  | *  Environment: development
web-1                  | *          PID: 1
web-1                  | * Listening on http://0.0.0.0:3000
web-1                  | Use Ctrl-C to stop`
