### ISSUE TITLE
sequences are not being created by ActiveRecord with cockroachdb adapter

### ISSUE THREAD

**Issue by willie** [cockroachdb/activerecord-cockroachdb-adapter#33]
As noted here, http://www.thekidds.org/blog/2012/07/27/active-record-postgres-and-sequence-naming/, when rails generates a model with Postgres, it creates a sequence.

I am not finding that behavior to carryover into using the CockroachDB adapter. Is there something where it has to coordinate with Active Record in a specific way?

(Yes, I know we should be using UUIDs, etc., but I'm looking at how we migrate existing Rails projects that use MySQL, and I'd rather be on CockroachDB first, then fix that problem.)

**Comment by BuonOmo** [comment]
Hey, I'm cleaning up issues here. The link being now dead I have a hard time understanding the context of this issue. I'll close now, also knowing that we do have sequence management in the gem. Hopefully the error doesn't stand anymore. Anyone feel free to comment below if needed
