### ISSUE TITLE
Request to add PG::TRSerializationFailure handling to 6-1-stable

### ISSUE THREAD

**Issue by harelsafra** [cockroachdb/activerecord-cockroachdb-adapter#335]
Hi,
We migrated to CRDB and are getting sporadic PG::TRSerializationFailure errors, currently using the PG driver.
We're using rails 6.1.7.3 and so need to use the 6.1 gem, and it looks like it doesn't catch and retry PG::TRSerializationFailure errors
https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/6-1-stable/lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb
While the master branch does have this handling
https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/0f9a4181080e5b1ae2040fc91c5b0d891c248505/lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb#L58

Can this functionality please be added to 6.1? 
I tried to fork the repo and add this but I got a lot of failing test cases, even before I changed anything 😢 

Thanks

**Comment by BuonOmo** [comment]
@harelsafra there are indeed failing tests around this (see #333). I'm working on it now. I don't feel safe backporting this knowing that there are some unresolved bugs.

**Comment by harelsafra** [comment]
Thanks @BuonOmo , I'll follow #333
