### ISSUE TITLE
savepoint monkey-patching is obsolete

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/activerecord-cockroachdb-adapter#42]
With savepoint support coming in 20.1, the customizations this library does around savepoints are no longer needed (for the new crdb version). They seem to break nested transactions.

At least:
https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/f14037d3d9d7dbe5eb1ea1f46ef8eb3ca5031107/lib/active_record/connection_adapters/cockroachdb_adapter.rb#L126

https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/f14037d3d9d7dbe5eb1ea1f46ef8eb3ca5031107/lib/active_record/connection_adapters/cockroachdb/transaction_manager.rb

Btw, maybe this library is not needed at all any more? I couldn't tell what's in in.

**Comment by BuonOmo** [comment]
This is not the case anymore!
