### ISSUE TITLE
ActiveRecord 4 Support

### ISSUE THREAD

**Issue by SuperQ** [cockroachdb/activerecord-cockroachdb-adapter#6]
Is there a chance this will work with ActiveRecord 4.x?

If not, is there any plan to add support for this?

**Comment by jordanlewis** [comment]
Hi @SuperQ, AFAIK this plugin will not work with ActiveRecord 4.x and as of the moment we don't have plans to support it.

**Comment by SuperQ** [comment]
Ok, thanks for checking.  I guess we need to get a move on https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/5555 so we can try using this. 😄
