### ISSUE TITLE
Update version to follow ActiveRecord versioning

### ISSUE THREAD

**Issue by alimi** [cockroachdb/activerecord-cockroachdb-adapter#74]
Other 3rd party ActiveRecord adapters like [ActiveRecord SQL Server Adapter](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter) and [Oracle Enhanced](https://github.com/rsim/oracle-enhanced) release versions that line up with the ActiveRecord version they work against. For example, [Oracle Enhanced 6.0.0](https://rubygems.org/gems/activerecord-oracle_enhanced-adapter/versions/6.0.0) works with ActiveRecord 6.0.0. This makes it easy to quickly see what ActiveRecord versions the 3rd party adapters support. We can do the same thing with ActiveRecord CockroachDB Adapter.

To do this, we'd want to do something like

- [x] create a tag/release for the currently published gem, 0.2.3, at 66a9c65dda8774a233149c9c1234faea8be1ce04
- [x] create a branch for development against ActiveRecord 5.2
- [x] update ActiveRecord CockroachDB Adapter's [version to 5.2](https://github.com/cockroachdb/activerecord-cockroachdb-adapter/blob/492fa2bc386cc6301a3f8c68f8dfb2768cbbb85b/activerecord-cockroachdb-adapter.gemspec#L7)
- [x] create a tag/release for ActiveRecord CockroachDB Adapter 5.2
- [x] publish ActiveRecord CockroachDB Adapter 5.2 to rubygems

We could then follow the same process for development against ActiveRecord 6.0.

**Comment by rafiss** [comment]
For now, we will keep using the master branch to develop 5.2. Once we start working on 6.0 support, we can cut a new branch for 5.2 only, and use master for 6.0.

The gem is published here: https://rubygems.org/gems/activerecord-cockroachdb-adapter/versions/5.2.0.beta2
